from ragas import evaluate, EvaluationDataset
from ragas.llms import LangchainLLMWrapper
from ragas.metrics import LLMContextRecall, Faithfulness, LLMContextPrecisionWithReference
from src.week_2_primegate.retrieval import search_chapter
from src.week_2_primegate.agent import chain, model, langfuse_handler

from ragas.run_config import RunConfig

run_config = RunConfig(
    timeout=180,
    max_retries=10,
    max_wait=60,
    max_workers=2,
)

sample_queries = [
    "What are the three critical elements an entrepreneur must solve for success?",
    "What percentage of all businesses in the United States are small, according to the SBA?",
    "Who founded Apple and how much capital did they initially raise?",
    "What is a cookie-cutter business plan and why does the text advise against it?",
    "How many pages should a small business plan typically be?",
    "What is the difference between a venture capital-backed business and an entrepreneurial business?",
    "What does the term 'lean start-up' mean?",
    "What percentage of U.S. millionaires are self-employed?",
    "What happened to entrepreneurial business activity after World War II?",
    "What is the maximum number of employees the U.S. government uses to classify a small business?",
]

expected_responses = [
    "An effective sales generation model, sustainable operating profit margins, and being properly financed.",
    "99.9 percent of all businesses in the United States are small.",
    "Steve Jobs founded Apple with Steve Wozniak, raising approximately $1,600 by selling his microbus and Wozniak selling his calculator.",
    "A cookie-cutter business plan is a generic plan generated by online programs where you plug in information. The text advises against them because each business plan should have its own voice and be developed by the individual(s) contemplating the business.",
    "A small business plan should be relatively short, around 15 to 25 pages.",
    "A venture capital-backed business is well-funded by outside investors with a harvest plan to exit, while an entrepreneurial business is self-funded, oriented around positive cash flow, and designed around the founder's personal goals.",
    "Lean start-up means treating a start-up as an experiment, rapidly testing and adapting the business based on real customer feedback rather than pursuing a fixed idea.",
    "Almost two-thirds of U.S. millionaires are self-employed.",
    "Entrepreneurial business as a percentage of U.S. economic output began to decline following World War II, as the era favored big business.",
    "The U.S. government considers any business with fewer than 500 employees to be a small business.",
]

dataset = []

for query, reference in zip(sample_queries, expected_responses):
    retrieved_contexts = search_chapter(query)
    context = "\n\n".join(retrieved_contexts)

    response = chain.invoke(
        {"history": [], "input": query, "context": context},
        config={"callbacks": [langfuse_handler]},
    )

    dataset.append({
        "user_input": query,
        "retrieved_contexts": retrieved_contexts,
        "response": str(response.content),
        "reference": reference,
    })


evaluation_dataset = EvaluationDataset.from_list(dataset)


evaluator_llm = LangchainLLMWrapper(model)
result = evaluate(
    dataset=evaluation_dataset,
    metrics=[LLMContextPrecisionWithReference(), LLMContextRecall(), Faithfulness()],
    llm=evaluator_llm,
    run_config=run_config,
)

print(result)