[project]
name = "week-2-primegate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yazank", email = "yazank105@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "qdrant-client>=1.19.0",
]

[project.scripts]
week-2-primegate = "week_2_primegate:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
